CREATE TABLE [dbo].[CART]
(
	[AccountID] INT NOT NULL , 
    [ProductID] INT NOT NULL, 
    CONSTRAINT [PK_CART] PRIMARY KEY ([AccountID], [ProductID]), 
    CONSTRAINT [FK_CART_ACCOUNT] FOREIGN KEY ([AccountID]) REFERENCES [ACCOUNT]([Id]), 
    CONSTRAINT [FK_CART_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [PRODUCT]([Id])
)
