CREATE TABLE [dbo].[CART]
(
	[Id] INT NOT NULL IDENTITY(-2147483648, 1) ,
	[AuthUserID] NVARCHAR(120) NOT NULL , 
    [ProductID] NVARCHAR(20) NOT NULL, 
    CONSTRAINT [PK_CART] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_CART_ACCOUNT] FOREIGN KEY ([Id]) REFERENCES [ACCOUNT]([Id]), 
    CONSTRAINT [FK_CART_PRODUCT] FOREIGN KEY ([Id]) REFERENCES [PRODUCT]([Id])
)
