CREATE TABLE [dbo].[COMBO_PRODUCT]
(
	[ComboId] INT NOT NULL, 
    [ProductID] CHAR(9) NOT NULL, 
    [Number] INT NOT NULL, 
    [Unit] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_COMBO_PRODUCT_COMBO] FOREIGN KEY ([ComboId]) REFERENCES [COMBO]([Id]), 
    CONSTRAINT [PK_COMBO_PRODUCT] PRIMARY KEY ([ComboId]) 
)
