CREATE TABLE [dbo].[ORDER_PRODUCT]
(
    [OrderID] INT NOT NULL, 
    [ProductID] INT NOT NULL, 
    [Number] INT NOT NULL, 
    CONSTRAINT [FK_ORDER_PRODUCT_ORDER] FOREIGN KEY ([OrderID]) REFERENCES [ORDER]([Id]), 
    CONSTRAINT [FK_ORDER_PRODUCT_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [PRODUCT]([Id]), 
    CONSTRAINT [PK_ORDER_PRODUCT] PRIMARY KEY ([OrderID], [ProductID]) 
)
