CREATE TABLE [dbo].[ORDER_PRODUCT]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(-2147483648, 1), 
    [OrderID] INT NOT NULL, 
    [ProductID] INT NOT NULL, 
    [Number] INT NOT NULL, 
    CONSTRAINT [FK_ORDER_PRODUCT_ORDER] FOREIGN KEY ([OrderID]) REFERENCES [ORDER]([Id]), 
    CONSTRAINT [FK_ORDER_PRODUCT_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [PRODUCT]([Id])
)
