CREATE TABLE [dbo].[PRODUCT_ATTRIBUTE]
(
    [ProductID] INT NOT NULL, 
    [AttributeID] INT NOT NULL, 
    [Value] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_PRODUCT_ATTRIBUTE_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [PRODUCT]([Id]), 
    CONSTRAINT [FK_PRODUCT_ATTRIBUTE_ATTRIBUTE] FOREIGN KEY ([AttributeID]) REFERENCES [ATTRIBUTE]([Id]), 
    CONSTRAINT [PK_PRODUCT_ATTRIBUTE] PRIMARY KEY ([ProductID], [AttributeID])
)
