CREATE TABLE [dbo].[PRODUCT]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(-2147483648, 1), 
    [Name] NVARCHAR(100) NOT NULL, 
    [Price] MONEY NOT NULL, 
    [Discount] MONEY NULL, 
    [Remain] SMALLINT NOT NULL, 
    [Detail_Path] NVARCHAR(200) NULL, 
    [Image_Path] NVARCHAR(200) NULL, 
    [Series] NVARCHAR(50) NULL, 
    [Company] NVARCHAR(50) NOT NULL, 
    [Need] NVARCHAR(50) NULL
)
