CREATE TABLE [dbo].[PRODUCT]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(-2147483648, 1), 
    [TypeID] INT NOT NULL,
    [Name] NVARCHAR(100) NOT NULL, 
    [Price] MONEY NOT NULL, 
    [Discount] MONEY NULL, 
    [Remain] SMALLINT NOT NULL, 
    [Detail_Path] NVARCHAR(200) NULL, 
    [Image_Path] NVARCHAR(200) NULL, 
    [Series] NVARCHAR(50) NULL, 
    [CompanyID] INT NOT NULL, 
    [NeedID] INT NULL, 
    CONSTRAINT [FK_PRODUCT_TYPE] FOREIGN KEY ([TypeID]) REFERENCES [TYPE]([Id]), 
    CONSTRAINT [FK_PRODUCT_COMPANY] FOREIGN KEY ([CompanyID]) REFERENCES [COMPANY]([Id]), 
    CONSTRAINT [FK_PRODUCT_NEED] FOREIGN KEY ([NeedID]) REFERENCES [NEED]([Id]) 
)
